export const INITIAL_CENTER = { lat: 53.6798865, lng: 9.3726795 };
export const INITIAL_ZOOM = 8;
export const MAX_POPULAR_WORDS = 5;
export const IDLE_UPDATE = true;
export const REFRESH_INTERVAL = 60000;
export const ANALYSIS_REST_HOST = "${ANALYSIS_REST_HOST}".replace(/['"]+/g, '');
export const ANALYSIS_REST_PORT = "${ANALYSIS_REST_PORT}".replace(/['"]+/g, '');
export const DATA_MANAGEMENT_HOST = "${DATA_MANAGEMENT_HOST}".replace(/['"]+/g, '');
export const DATA_MANAGEMENT_PORT = "${DATA_MANAGEMENT_PORT}".replace(/['"]+/g, '');
